### ISSUE TITLE
Re-enable jruby in the CI

### ISSUE THREAD

**Issue by postmodern** [ronin-rb/ronin-web#26]
Get specs passing on jruby.

**Comment by postmodern** [comment]
Blocked by some weird `nokogiri` parsing differences under JRuby:

```
  1) Ronin::Web::HTML.parse must parse an HTML String and return a Nokogiri::HTML::Document
     Failure/Error: expect(doc.at('body').inner_text).to eq("Hello")
     
       expected: "Hello"
            got: "Hello\n"
     
       (compared using ==)
     
       Diff:
         <The diff is empty, are your objects producing identical `#inspect` output?>
     # ./spec/html_spec.rb:18:in `block in <main>'

  2) Ronin::Web.html should be able to parse HTML
     Failure/Error: expect(doc.at('body').inner_text).to eq("Hello")
     
       expected: "Hello"
            got: "Hello\n      "
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,3 @@
        Hello
       +      
       
     # ./spec/web_spec.rb:19:in `block in <main>'
```
